name: Test in jdk 11

on: [push]

jobs:
  matrix:

    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build product with Maven
      run: mvn -B clean install -DskipTests --file pom.xml
    - name: Set up JDK 11
      uses: joschi/setup-jdk@v1
      with:
        java-version: openjdk11
    - name: Test product with Maven
      run: mvn -B clean install --file integration/pom.xml

