name: Java CI

on: [push]

jobs:
  matrix:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest, macOS-latest]
    steps:
    - name: Support longpaths
      run: git config --system core.longpaths true
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B clean install -P smoke-tests --file pom.xml
#  windows:
#
#    runs-on: windows-latest

#    steps:
#    - uses: actions/checkout@v1
#    - name: Set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.8
#    - name: Build with Maven
#      run: mvn -B clean install -P smoke-tests --file pom.xml
#  
#  mac:
#
#    runs-on: macOS-latest
#
#    steps:
#    - uses: actions/checkout@v1
#    - name: Set up JDK 1.8
#      uses: actions/setup-java@v1
#      with:
#        java-version: 1.8
#    - name: Build with Maven
#      run: mvn -B clean install -P smoke-tests --file pom.xml
